### ISSUE TITLE
Problem importing org.sonar.plugins.java.Java in MyJavaRulesDefinition.java

### ISSUE THREAD

**Issue by vaibhav9518** [SonarSource/sonar-custom-rules-examples#10]
I am trying to build the project to add custom rules following this [page](https://docs.sonarqube.org/display/PLUG/Writing+Custom+Java+Rules+101)
but the project shows the error importing org.sonar.plugins.java.Java and I am not able to build it.

**Comment by shengulong** [comment]
I have the same problem.how to solve it?

**Comment by shengulong** [comment]
try this:
i solve it by the following
//import org.sonar.plugins.java.Java;

@Override
  public void define(Context context) {
    NewRepository repository = context
      .createRepository(REPOSITORY_KEY,"java")
      .setName("MyCompany Custom Repository");

**Comment by agigleux** [comment]
As a workaround has been found. I close it.

**Comment by sonata82** [comment]
I'm sorry, but I don't think a workaround which can be found in this issue is the same as "resolved".

**Comment by erikgoz** [comment]
Workaround my ass

**Comment by fededamian** [comment]
I was having this issue while trying to import and build the project in IntelliJ IDEA.

I found a procedure that solved the issue [here](https://stackoverflow.com/questions/23366300/sonarqube-custom-java-rules?rq=1).

Basically, you have to comment the `<type>sonar-plugin</type>` line in the pom.xml file, and that will trigger the "Maven project needs to be imported" pop-up, where you have to click "Import Changes".

After that, uncomment back the line, and save the file, but do not import the changes again, since that will revert to the previous state.

I am not sure why that line affects the ability to import the package, but if someone is willing to explain it it would be great, and maybe we can change the commenting / uncommenting steps with something permanent and cleaner.
